// Generated by Framer (cf4c6d7)
import siteMetadata from "https://framerusercontent.com/modules/k1n6xSOdatbWDfzmqJ9Z/R5jIEo2taYZ7WqGJ5KJK/siteMetadata.js";
export default function metadata(params, activeLocale) {
  return {
    breakpoints: [{ hash: "72rtr7" }],
    description: siteMetadata(params, activeLocale).description,
    elements: {},
    robots: "max-image-preview:large",
    serializationId: "framer-6wgQi",
    title: siteMetadata(params, activeLocale).title || "Home",
    viewport: "width=800",
  };
}
export const metadataVersion = 1;
export const __FramerMetadata__ = {
  exports: {
    metadataVersion: {
      type: "variable",
      annotations: { framerContractVersion: "1" },
    },
    default: { type: "function", annotations: { framerContractVersion: "1" } },
    __FramerMetadata__: { type: "variable" },
  },
};
