// Generated by Framer (bdfb9a2)
import { jsx as _jsx } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ControlType,
  cx,
  useActiveVariantCallback,
  useOnVariantChange,
  useVariantState,
  withCSS,
} from "src/components/framer.jsx";
import { LayoutGroup, motion } from "framer-motion";
import * as React from "react";
const cycleOrder = ["GYLLZ6QvO", "Ue8ToJeuA", "a_m8iD3YR"];
const variantClassNames = {
  a_m8iD3YR: "framer-v-18wmnpd",
  GYLLZ6QvO: "framer-v-kul5sj",
  Ue8ToJeuA: "framer-v-o0x4lh",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants === null || variants === void 0
    ? void 0
    : variants.forEach(
        (variant) =>
          variant && Object.assign(nextOverrides, overrides[variant]),
      );
  return nextOverrides;
}
const humanReadableVariantMap = {
  "Variant 1": "GYLLZ6QvO",
  "Variant 2": "Ue8ToJeuA",
  "Variant 3": "a_m8iD3YR",
};
const transitions = {
  default: {
    damping: 60,
    delay: 0,
    duration: 0,
    ease: [0, 0, 1, 1],
    mass: 1,
    stiffness: 500,
    type: "tween",
  },
  Ue8ToJeuA: {
    damping: 80,
    delay: 0,
    duration: 1,
    ease: [0.44, 0, 0.56, 1],
    mass: 1,
    stiffness: 500,
    type: "tween",
  },
};
const Component = /*#__PURE__*/ React.forwardRef(function (
  {
    id,
    style,
    className,
    width,
    height,
    layoutId,
    variant: outerVariant = "GYLLZ6QvO",
    ...restProps
  },
  ref,
) {
  const outerVariantId = humanReadableVariantMap[outerVariant];
  const variant = outerVariantId || outerVariant;
  const {
    baseVariant,
    classNames,
    gestureVariant,
    setGestureState,
    setVariant,
    transition,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "GYLLZ6QvO",
    transitions,
    variant,
    variantClassNames,
  });
  const layoutDependency = variants.join("-") + restProps.layoutDependency;
  const { activeVariantCallback, delay } =
    useActiveVariantCallback(baseVariant);
  const onAppearkdheef = activeVariantCallback(async (...args) => {
    await delay(() => setVariant("Ue8ToJeuA"), 300);
  });
  const onAppearv8x4uq = activeVariantCallback(async (...args) => {
    await delay(() => setVariant("a_m8iD3YR"), 1400);
  });
  const onAppear1mh9shn = activeVariantCallback(async (...args) => {
    await delay(() => setVariant("GYLLZ6QvO"), 300);
  });
  useOnVariantChange(baseVariant, {
    a_m8iD3YR: onAppear1mh9shn,
    default: onAppearkdheef,
    Ue8ToJeuA: onAppearv8x4uq,
  });
  const defaultLayoutId = React.useId();
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId,
    children: /*#__PURE__*/ _jsx(motion.div, {
      initial: variant,
      animate: variants,
      onHoverStart: () => setGestureState({ isHovered: true }),
      onHoverEnd: () => setGestureState({ isHovered: false }),
      onTapStart: () => setGestureState({ isPressed: true }),
      onTap: () => setGestureState({ isPressed: false }),
      onTapCancel: () => setGestureState({ isPressed: false }),
      className: cx("framer-7htEU", classNames),
      style: { display: "contents" },
      children: /*#__PURE__*/ _jsx(motion.div, {
        ...restProps,
        className: cx("framer-kul5sj", className),
        "data-framer-name": "Variant 1",
        "data-highlight": true,
        layoutDependency: layoutDependency,
        layoutId: "GYLLZ6QvO",
        ref: ref,
        style: { ...style },
        transition: transition,
        ...addPropertyOverrides(
          {
            a_m8iD3YR: { "data-framer-name": "Variant 3" },
            Ue8ToJeuA: { "data-framer-name": "Variant 2" },
          },
          baseVariant,
          gestureVariant,
        ),
        children: /*#__PURE__*/ _jsx(motion.div, {
          className: "framer-drrgx7",
          "data-framer-name": "Gradient",
          layoutDependency: layoutDependency,
          layoutId: "Qk2qkqiTF",
          style: {
            background:
              "linear-gradient(90deg, rgba(255, 255, 255, 0) 0%, hsl(0, 0%, 100%) 100%)",
          },
          transition: transition,
        }),
      }),
    }),
  });
});
const css = [
  '.framer-7htEU [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-7htEU .framer-1t8b4z3 { display: block; }",
  ".framer-7htEU .framer-kul5sj { height: 34px; overflow: hidden; position: relative; width: 234px; }",
  ".framer-7htEU .framer-drrgx7 { bottom: 0px; flex: none; left: -70px; overflow: hidden; position: absolute; top: 0px; width: 70px; }",
  ".framer-7htEU.framer-v-o0x4lh .framer-drrgx7 { left: unset; right: -70px; }",
  ".framer-7htEU.framer-v-18wmnpd .framer-drrgx7 { bottom: unset; height: 1px; }",
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 34
 * @framerIntrinsicWidth 234
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"Ue8ToJeuA":{"layout":["fixed","fixed"]},"a_m8iD3YR":{"layout":["fixed","fixed"]}}}
 */ const FramerDQr_W3F0I = withCSS(Component, css, "framer-7htEU");
export default FramerDQr_W3F0I;
FramerDQr_W3F0I.displayName = "Shimmer Top";
FramerDQr_W3F0I.defaultProps = { height: 34, width: 234 };
addPropertyControls(FramerDQr_W3F0I, {
  variant: {
    options: ["GYLLZ6QvO", "Ue8ToJeuA", "a_m8iD3YR"],
    optionTitles: ["Variant 1", "Variant 2", "Variant 3"],
    title: "Variant",
    type: ControlType.Enum,
  },
});
addFonts(FramerDQr_W3F0I, []);
export const __FramerMetadata__ = {
  exports: {
    default: {
      type: "reactComponent",
      name: "FramerDQr_W3F0I",
      slots: [],
      annotations: {
        framerIntrinsicWidth: "234",
        framerIntrinsicHeight: "34",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"Ue8ToJeuA":{"layout":["fixed","fixed"]},"a_m8iD3YR":{"layout":["fixed","fixed"]}}}',
        framerContractVersion: "1",
      },
    },
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./DQr_W3F0I.map
