// Generated by Framer (cf4c6d7)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ComponentViewportProvider,
  ControlType,
  cx,
  getFonts,
  Link,
  RichText,
  SmartComponentScopedContainer,
  useActiveVariantCallback,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
  withFX,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
import Grain from "https://framerusercontent.com/modules/cKGD16u2MGB7MfqfVXFp/wiztTCbXokZrMicHAmZc/Grain.js";
import Particles from "https://framerusercontent.com/modules/wb6ZrZlCLNQ5HHBJtNND/c1GLxCsQBQvlLXhkz7er/Particles.js";
import ShimmerTop from "https://framerusercontent.com/modules/nUB5S7ynjeeCGQZsxWPO/GMeBpvbwLkkHvF0zwADm/DQr_W3F0I.js";
import Stars from "https://framerusercontent.com/modules/fGUdVqcDZJzXWaGFzTDr/bnwLKQ5VKXo0vouT29AB/IZbUeNBW6.js";
import ShimmerBottom from "https://framerusercontent.com/modules/hNERs3qPQYbkrVQ9SV9B/Qo40vWlyOhjrVGHHk43u/JgOnmcTtx.js";
const ParticlesFonts = getFonts(Particles);
const SmartComponentScopedContainerWithFX = withFX(
  SmartComponentScopedContainer,
);
const MotionDivWithFX = withFX(motion.div);
const GrainFonts = getFonts(Grain);
const ShimmerBottomFonts = getFonts(ShimmerBottom);
const ShimmerTopFonts = getFonts(ShimmerTop);
const StarsFonts = getFonts(Stars);
const MotionAWithFX = withFX(motion.a);
const cycleOrder = ["bFkwa7f71", "SZsOVWB1D"];
const serializationHash = "framer-SOlIw";
const variantClassNames = {
  bFkwa7f71: "framer-v-jpu5kq",
  SZsOVWB1D: "framer-v-1eh7o13",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant]),
  );
  return nextOverrides;
}
const transition1 = {
  damping: 100,
  delay: 0,
  mass: 1,
  stiffness: 500,
  type: "spring",
};
const transition2 = {
  delay: 0,
  duration: 2,
  ease: [0.44, 0, 0.56, 1],
  type: "tween",
};
const animation = {
  opacity: 0.5,
  rotate: 0,
  rotateX: 0,
  rotateY: 0,
  scale: 1,
  skewX: 0,
  skewY: 0,
  x: 0,
  y: 0,
};
const animation1 = {
  opacity: 0.6,
  rotate: 0,
  rotateX: 0,
  rotateY: 0,
  scale: 1,
  skewX: 0,
  skewY: 0,
  x: 0,
  y: 0,
};
const transformTemplate1 = (_, t) => `translateY(-50%) ${t}`;
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)],
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = {
  "Variant 1": "bFkwa7f71",
  "Variant 2": "SZsOVWB1D",
};
const getProps = ({ height, id, width, ...props }) => {
  return {
    ...props,
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "bFkwa7f71",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const { style, className, layoutId, variant, ...restProps } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "bFkwa7f71",
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const { activeVariantCallback, delay } =
    useActiveVariantCallback(baseVariant);
  const onMouseEnter1yhznkx = activeVariantCallback(async (...args) => {
    setVariant("SZsOVWB1D");
  });
  const onMouseLeavenbc2mh = activeVariantCallback(async (...args) => {
    setVariant("bFkwa7f71");
  });
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsxs(motion.div, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            scopingClassNames,
            "framer-jpu5kq",
            className,
            classNames,
          ),
          "data-framer-name": "Variant 1",
          layoutDependency: layoutDependency,
          layoutId: "bFkwa7f71",
          ref: refBinding,
          style: { backgroundColor: "rgb(17, 17, 17)", ...style },
          variants: { SZsOVWB1D: { backgroundColor: "rgb(16, 0, 46)" } },
          ...addPropertyOverrides(
            { SZsOVWB1D: { "data-framer-name": "Variant 2" } },
            baseVariant,
            gestureVariant,
          ),
          children: [
            /*#__PURE__*/ _jsx(ComponentViewportProvider, {
              children: /*#__PURE__*/ _jsx(
                SmartComponentScopedContainerWithFX,
                {
                  __framer__loop: animation,
                  __framer__loopEffectEnabled: true,
                  __framer__loopRepeatDelay: 0,
                  __framer__loopRepeatType: "mirror",
                  __framer__loopTransition: transition2,
                  __perspectiveFX: false,
                  __smartComponentFX: true,
                  __targetOpacity: 0,
                  className: "framer-dli12o-container",
                  isAuthoredByUser: true,
                  isModuleExternal: true,
                  layoutDependency: layoutDependency,
                  layoutId: "Ng4NyTHL8-container",
                  nodeId: "Ng4NyTHL8",
                  rendersWithMotion: true,
                  scopeId: "kZuk8wIV6",
                  style: { opacity: 0 },
                  variants: { SZsOVWB1D: { opacity: 1 } },
                  ...addPropertyOverrides(
                    { SZsOVWB1D: { __targetOpacity: 1 } },
                    baseVariant,
                    gestureVariant,
                  ),
                  children: /*#__PURE__*/ _jsx(Particles, {
                    background: "rgba(0, 0, 0, 0)",
                    clickOptions: { clickEnabled: false, clickModes: "push" },
                    color: "rgb(179, 116, 253)",
                    colors: [],
                    densityOptions: {
                      densityArea: 5e3,
                      densityEnable: false,
                      densityFactor: 50,
                    },
                    fpsOptions: 60,
                    height: "100%",
                    hoverOptions: {
                      hoverEnabled: false,
                      hoverForce: 10,
                      hoverModes: "none",
                      hoverParallax: true,
                      hoverSmooth: 10,
                    },
                    id: "Ng4NyTHL8",
                    layoutId: "Ng4NyTHL8",
                    linksOptions: {
                      linksColor: "rgb(255, 255, 255)",
                      linksDistance: 100,
                      linksEnabled: false,
                      linksOpacity: 0.2,
                      linksWidth: 1,
                    },
                    modeOptions: {
                      bubbleDistance: 100,
                      bubbleDuration: 0.4,
                      bubbleSize: 40,
                      connectDistance: 100,
                      connectLinksOpacity: 0.2,
                      connectRadius: 50,
                      grabDistance: 100,
                      grabLinksOpacity: 0.2,
                      pushQuantity: 4,
                      removeQuantity: 4,
                      repulseDistance: 200,
                      repulseDuration: 1.2,
                      trailDelay: 0.1,
                      trailQuantity: 10,
                    },
                    moveOptions: {
                      moveAttractDistance: 100,
                      moveAttractEnabled: false,
                      moveDirection: "none",
                      moveEnabled: true,
                      moveGravityAcceleration: 1,
                      moveGravityEnabled: false,
                      moveGravityMaxSpeed: 2,
                      moveOut: "none",
                      moveRandom: false,
                      moveSpeed: 0.5,
                      moveSpinAcceleration: 1,
                      moveSpinEnabled: true,
                      moveStraight: false,
                      moveTrailAmount: 100,
                      moveTrailEnabled: false,
                      moveVibrate: false,
                    },
                    number: 70,
                    opacityOptions: {
                      opacity: 0,
                      opacityMax: 1,
                      opacityMin: 0,
                      opacityType: false,
                    },
                    particlesID: "One",
                    radius: 0,
                    rotateOptions: {
                      rotateAnimation: false,
                      rotateDirection: "random",
                      rotateSpeed: 5,
                      rotateSync: false,
                      rotateValue: 0,
                    },
                    shapeOptions: {
                      characterType: "✦",
                      imageHeight: 100,
                      imageSource:
                        "https://framerusercontent.com/images/rd7N7uveozewZoAlg7b2TGj7cew.gif",
                      imageWidth: 100,
                      shapeType: "character",
                    },
                    sizeOptions: {
                      size: 1,
                      sizeMax: 6,
                      sizeMin: 3,
                      sizeType: false,
                    },
                    style: { height: "100%", width: "100%" },
                    width: "100%",
                  }),
                },
              ),
            }),
            /*#__PURE__*/ _jsx(motion.div, {
              className: "framer-qjugxw",
              "data-framer-name": "Vignette",
              layoutDependency: layoutDependency,
              layoutId: "nEDcdhmwA",
              style: {
                background:
                  "radial-gradient(35.3% 37% at 50% 50%, rgba(16, 0, 46, 0) 0%, hsl(261, 100%, 9%) 100%)",
                opacity: 0,
              },
              variants: { SZsOVWB1D: { opacity: 1 } },
            }),
            /*#__PURE__*/ _jsx(MotionDivWithFX, {
              __framer__loop: animation,
              __framer__loopEffectEnabled: true,
              __framer__loopRepeatDelay: 0,
              __framer__loopRepeatType: "mirror",
              __framer__loopTransition: transition2,
              __perspectiveFX: false,
              __smartComponentFX: true,
              __targetOpacity: 1,
              className: "framer-16qpgtq",
              "data-framer-name": "Outer Glow",
              layoutDependency: layoutDependency,
              layoutId: "pzKCqWSPR",
              style: {
                borderBottomLeftRadius: 34,
                borderBottomRightRadius: 34,
                borderTopLeftRadius: 34,
                borderTopRightRadius: 34,
                boxShadow: "0px 0px 0px 0px rgba(146, 56, 255, 0)",
              },
              variants: {
                SZsOVWB1D: {
                  boxShadow: "0px 0px 280px 60px rgba(146, 56, 255, 0.4)",
                },
              },
            }),
            /*#__PURE__*/ _jsx(ComponentViewportProvider, {
              children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                className: "framer-1u8lxmk-container",
                isAuthoredByUser: true,
                isModuleExternal: true,
                layoutDependency: layoutDependency,
                layoutId: "efnLCb_sN-container",
                nodeId: "efnLCb_sN",
                rendersWithMotion: true,
                scopeId: "kZuk8wIV6",
                style: { opacity: 0 },
                variants: { SZsOVWB1D: { opacity: 1 } },
                children: /*#__PURE__*/ _jsx(Grain, {
                  height: "100%",
                  id: "efnLCb_sN",
                  layoutId: "efnLCb_sN",
                  opacity: 0.03,
                  style: { height: "100%", width: "100%" },
                  width: "100%",
                }),
              }),
            }),
            /*#__PURE__*/ _jsx(MotionDivWithFX, {
              __framer__loop: animation,
              __framer__loopEffectEnabled: true,
              __framer__loopRepeatDelay: 0,
              __framer__loopRepeatType: "mirror",
              __framer__loopTransition: transition2,
              __perspectiveFX: false,
              __smartComponentFX: true,
              __targetOpacity: 0,
              className: "framer-imovt7",
              "data-framer-name": "Focus Ring",
              layoutDependency: layoutDependency,
              layoutId: "ayg5Y2g4u",
              style: {
                background:
                  "radial-gradient(68.5% 119.73800000000001% at 49.1% 100%, #af78f5 0%, #7438ff 100%)",
                borderBottomLeftRadius: 39,
                borderBottomRightRadius: 39,
                borderTopLeftRadius: 39,
                borderTopRightRadius: 39,
                boxShadow: "0px 0px 0px 0px rgba(15, 7, 32, 0)",
                opacity: 0,
              },
              variants: {
                SZsOVWB1D: {
                  boxShadow: "0px 16px 32px 0px rgb(15, 7, 32)",
                  opacity: 0.5,
                },
              },
              ...addPropertyOverrides(
                { SZsOVWB1D: { __targetOpacity: 0.5 } },
                baseVariant,
                gestureVariant,
              ),
            }),
            /*#__PURE__*/ _jsx(Link, {
              motionChild: true,
              nodeId: "h7IGoA92Z",
              scopeId: "kZuk8wIV6",
              ...addPropertyOverrides(
                {
                  SZsOVWB1D: {
                    href: { webPageId: "augiA20Il" },
                    openInNewTab: false,
                  },
                },
                baseVariant,
                gestureVariant,
              ),
              children: /*#__PURE__*/ _jsxs(MotionAWithFX, {
                __framer__loop: animation1,
                __framer__loopEffectEnabled: true,
                __framer__loopRepeatDelay: 0,
                __framer__loopRepeatType: "mirror",
                __framer__loopTransition: transition2,
                __perspectiveFX: false,
                __smartComponentFX: true,
                __targetOpacity: 1,
                className: "framer-1b9mn3w framer-bubtv1",
                "data-border": true,
                "data-framer-name": "Button",
                "data-highlight": true,
                layoutDependency: layoutDependency,
                layoutId: "h7IGoA92Z",
                onMouseEnter: onMouseEnter1yhznkx,
                style: {
                  "--border-bottom-width": "0px",
                  "--border-color": "rgba(255, 255, 255, 0.1)",
                  "--border-left-width": "0px",
                  "--border-right-width": "0px",
                  "--border-style": "solid",
                  "--border-top-width": "1px",
                  borderBottomLeftRadius: 34,
                  borderBottomRightRadius: 34,
                  borderTopLeftRadius: 34,
                  borderTopRightRadius: 34,
                  boxShadow:
                    "0px 0px 0px 0px rgba(32, 8, 73, 0), 0px 0px 0px 0px rgba(115, 59, 247, 0), inset 0px 1px 0px 0px rgba(255, 255, 255, 0.2), 0px 1px 0px 0px rgba(0, 0, 0, 0.2), 0px 0px 0px 0px rgba(91, 61, 199, 0)",
                },
                variants: {
                  SZsOVWB1D: {
                    "--border-bottom-width": "1px",
                    "--border-left-width": "1px",
                    "--border-right-width": "1px",
                    background:
                      "linear-gradient(180deg, #8855ff 0%, #783dff 100%)",
                    boxShadow:
                      "0px 16px 32px 0px hsla(262, 80%, 16%, 0.3), 0px 16px 32px 0px rgba(115, 59, 247, 0.6), inset 0px 1px 0px 0px rgba(255, 255, 255, 0.2), 0px 1px 0px 0px rgba(0, 0, 0, 0.2), 0px 0px 120px 0px rgb(91, 61, 199)",
                  },
                },
                ...addPropertyOverrides(
                  {
                    SZsOVWB1D: {
                      onMouseEnter: undefined,
                      onMouseLeave: onMouseLeavenbc2mh,
                    },
                  },
                  baseVariant,
                  gestureVariant,
                ),
                children: [
                  /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                    children: /*#__PURE__*/ _jsx(
                      SmartComponentScopedContainer,
                      {
                        className: "framer-zasdou-container",
                        layoutDependency: layoutDependency,
                        layoutId: "kPvTUCcFW-container",
                        nodeId: "kPvTUCcFW",
                        rendersWithMotion: true,
                        scopeId: "kZuk8wIV6",
                        style: { opacity: 0 },
                        variants: { SZsOVWB1D: { opacity: 1 } },
                        children: /*#__PURE__*/ _jsx(ShimmerBottom, {
                          height: "100%",
                          id: "kPvTUCcFW",
                          layoutId: "kPvTUCcFW",
                          style: { height: "100%", width: "100%" },
                          variant: "JpA4D8_9J",
                          width: "100%",
                        }),
                      },
                    ),
                  }),
                  /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                    children: /*#__PURE__*/ _jsx(
                      SmartComponentScopedContainer,
                      {
                        className: "framer-itjxxg-container",
                        layoutDependency: layoutDependency,
                        layoutId: "OT0PuxVeO-container",
                        nodeId: "OT0PuxVeO",
                        rendersWithMotion: true,
                        scopeId: "kZuk8wIV6",
                        style: { opacity: 0 },
                        variants: { SZsOVWB1D: { opacity: 1 } },
                        children: /*#__PURE__*/ _jsx(ShimmerTop, {
                          height: "100%",
                          id: "OT0PuxVeO",
                          layoutId: "OT0PuxVeO",
                          style: { height: "100%", width: "100%" },
                          variant: "GYLLZ6QvO",
                          width: "100%",
                        }),
                      },
                    ),
                  }),
                  /*#__PURE__*/ _jsx(motion.div, {
                    className: "framer-1fg1g51",
                    "data-framer-name": "Inner Fill",
                    layoutDependency: layoutDependency,
                    layoutId: "yoPYuJ_BH",
                    style: {
                      backgroundColor: "rgb(29, 29, 29)",
                      borderBottomLeftRadius: 33,
                      borderBottomRightRadius: 33,
                      borderTopLeftRadius: 33,
                      borderTopRightRadius: 33,
                    },
                    variants: {
                      SZsOVWB1D: { backgroundColor: "rgb(118, 58, 254)" },
                    },
                    children: /*#__PURE__*/ _jsx(MotionDivWithFX, {
                      __framer__loop: animation,
                      __framer__loopEffectEnabled: true,
                      __framer__loopRepeatDelay: 0,
                      __framer__loopRepeatType: "mirror",
                      __framer__loopTransition: transition2,
                      __perspectiveFX: false,
                      __smartComponentFX: true,
                      __targetOpacity: 0,
                      className: "framer-d10052",
                      "data-framer-name": "Inner Glow",
                      layoutDependency: layoutDependency,
                      layoutId: "HtrpGHeIc",
                      style: {
                        background:
                          "radial-gradient(50% 50% at 50% 50%, hsl(271, 96%, 75%) 0%, rgba(118, 58, 254, 0) 100%)",
                        borderBottomLeftRadius: "50%",
                        borderBottomRightRadius: "50%",
                        borderTopLeftRadius: "50%",
                        borderTopRightRadius: "50%",
                        opacity: 0,
                      },
                      variants: { SZsOVWB1D: { opacity: 1 } },
                      ...addPropertyOverrides(
                        { SZsOVWB1D: { __targetOpacity: 1 } },
                        baseVariant,
                        gestureVariant,
                      ),
                    }),
                  }),
                  /*#__PURE__*/ _jsx(RichText, {
                    __fromCanvasComponent: true,
                    children: /*#__PURE__*/ _jsx(React.Fragment, {
                      children: /*#__PURE__*/ _jsx(motion.p, {
                        style: {
                          "--font-selector": "R0Y7TWFucm9wZS03MDA=",
                          "--framer-font-family":
                            '"Manrope", "Manrope Placeholder", sans-serif',
                          "--framer-font-size": "22px",
                          "--framer-font-weight": "700",
                          "--framer-letter-spacing": "-0.2px",
                          "--framer-text-color":
                            "var(--extracted-r6o4lv, rgb(255, 255, 255))",
                        },
                        children: /*#__PURE__*/ _jsx(motion.span, {
                          "data-text-fill": "true",
                          style: {
                            backgroundImage:
                              "linear-gradient(90deg, rgba(255, 255, 255, 0.4) 0%, rgba(255, 255, 255, 0.2) 100%)",
                          },
                          children: "Generate Site",
                        }),
                      }),
                    }),
                    className: "framer-1fcgudp",
                    fonts: ["GF;Manrope-700"],
                    layoutDependency: layoutDependency,
                    layoutId: "Etsn10HiD",
                    style: { "--extracted-r6o4lv": "rgb(255, 255, 255)" },
                    transformTemplate: transformTemplate1,
                    verticalAlignment: "top",
                    withExternalLayout: true,
                    ...addPropertyOverrides(
                      {
                        SZsOVWB1D: {
                          children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.p, {
                              style: {
                                "--font-selector": "R0Y7TWFucm9wZS03MDA=",
                                "--framer-font-family":
                                  '"Manrope", "Manrope Placeholder", sans-serif',
                                "--framer-font-size": "22px",
                                "--framer-font-weight": "700",
                                "--framer-letter-spacing": "-0.2px",
                                "--framer-text-color":
                                  "var(--extracted-r6o4lv, rgb(255, 255, 255))",
                              },
                              children: /*#__PURE__*/ _jsx(motion.span, {
                                "data-text-fill": "true",
                                style: {
                                  backgroundImage:
                                    "linear-gradient(90deg, rgb(255, 255, 255) 0%, rgb(255, 255, 255) 100%)",
                                },
                                children: "Generate Site",
                              }),
                            }),
                          }),
                        },
                      },
                      baseVariant,
                      gestureVariant,
                    ),
                  }),
                  /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                    height: 28,
                    width: "28px",
                    y:
                      (componentViewport?.y || 0) +
                      ((componentViewport?.height || 400) * 0.5000000000000002 -
                        34) +
                      20.000000000000014,
                    children: /*#__PURE__*/ _jsx(
                      SmartComponentScopedContainer,
                      {
                        className: "framer-iqczvg-container",
                        layoutDependency: layoutDependency,
                        layoutId: "oEdinggR3-container",
                        nodeId: "oEdinggR3",
                        rendersWithMotion: true,
                        scopeId: "kZuk8wIV6",
                        style: { opacity: 0.3 },
                        transformTemplate: transformTemplate1,
                        variants: { SZsOVWB1D: { opacity: 1 } },
                        children: /*#__PURE__*/ _jsx(Stars, {
                          height: "100%",
                          id: "oEdinggR3",
                          layoutId: "oEdinggR3",
                          style: { height: "100%", width: "100%" },
                          variant: "vlYcngcin",
                          width: "100%",
                          ...addPropertyOverrides(
                            { SZsOVWB1D: { variant: "so6iT3IIO" } },
                            baseVariant,
                            gestureVariant,
                          ),
                        }),
                      },
                    ),
                  }),
                ],
              }),
            }),
          ],
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-SOlIw.framer-bubtv1, .framer-SOlIw .framer-bubtv1 { display: block; }",
  ".framer-SOlIw.framer-jpu5kq { height: 400px; overflow: hidden; position: relative; width: 600px; }",
  ".framer-SOlIw .framer-dli12o-container { flex: none; height: 400px; left: calc(50.00000000000002% - 600px / 2); position: absolute; top: calc(50.00000000000002% - 400px / 2); width: 600px; }",
  ".framer-SOlIw .framer-qjugxw { bottom: 0px; flex: none; left: 0px; overflow: hidden; position: absolute; right: 0px; top: 0px; }",
  ".framer-SOlIw .framer-16qpgtq, .framer-SOlIw .framer-imovt7 { flex: none; height: 68px; left: calc(49.83333333333336% - 238px / 2); overflow: visible; position: absolute; top: calc(50.00000000000002% - 68px / 2); width: 238px; }",
  ".framer-SOlIw .framer-1u8lxmk-container { bottom: 0px; flex: none; left: 0px; pointer-events: none; position: absolute; right: 0px; top: 0px; }",
  ".framer-SOlIw .framer-1b9mn3w { cursor: pointer; flex: none; height: 68px; left: calc(49.83333333333336% - 238px / 2); overflow: hidden; position: absolute; top: calc(50.00000000000002% - 68px / 2); width: 238px; will-change: var(--framer-will-change-override, transform); }",
  ".framer-SOlIw .framer-zasdou-container { bottom: 0px; flex: none; height: 34px; left: 0px; position: absolute; right: 0px; }",
  ".framer-SOlIw .framer-itjxxg-container { flex: none; height: 34px; left: 0px; position: absolute; right: 0px; top: 0px; }",
  ".framer-SOlIw .framer-1fg1g51 { bottom: 0px; flex: none; left: 0px; overflow: visible; position: absolute; right: 0px; top: 0px; }",
  ".framer-SOlIw .framer-d10052 { bottom: -54px; flex: none; height: 103px; left: -9px; overflow: hidden; position: absolute; right: -10px; will-change: var(--framer-will-change-override, transform); }",
  ".framer-SOlIw .framer-1fcgudp { -webkit-user-select: none; cursor: pointer; flex: none; height: auto; overflow: visible; pointer-events: none; position: absolute; right: 29px; top: 47%; user-select: none; white-space: pre; width: auto; z-index: 1; }",
  ".framer-SOlIw .framer-iqczvg-container { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 28px); left: 25px; position: absolute; top: 50%; width: 28px; }",
  ".framer-SOlIw.framer-v-1eh7o13 .framer-imovt7 { height: 80px; left: calc(49.83333333333336% - 250px / 2); top: calc(50.00000000000002% - 80px / 2); width: 250px; }",
  ".framer-SOlIw.framer-v-1eh7o13 .framer-1b9mn3w { text-decoration: none; }",
  ".framer-SOlIw.framer-v-1eh7o13 .framer-1fg1g51 { bottom: 2px; overflow: hidden; top: 2px; will-change: var(--framer-will-change-override, transform); }",
  '.framer-SOlIw[data-border="true"]::after, .framer-SOlIw [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 400
 * @framerIntrinsicWidth 600
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"SZsOVWB1D":{"layout":["fixed","fixed"]}}}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerComponentViewportWidth true
 */ const FramerkZuk8wIV6 = withCSS(Component, css, "framer-SOlIw");
export default FramerkZuk8wIV6;
FramerkZuk8wIV6.displayName = "Button";
FramerkZuk8wIV6.defaultProps = { height: 400, width: 600 };
addPropertyControls(FramerkZuk8wIV6, {
  variant: {
    options: ["bFkwa7f71", "SZsOVWB1D"],
    optionTitles: ["Variant 1", "Variant 2"],
    title: "Variant",
    type: ControlType.Enum,
  },
});
addFonts(
  FramerkZuk8wIV6,
  [
    {
      explicitInter: true,
      fonts: [
        {
          family: "Manrope",
          source: "google",
          style: "normal",
          url: "https://fonts.gstatic.com/s/manrope/v15/xn7_YHE41ni1AdIRqAuZuw1Bx9mbZk4aE-_A87jxeN7B.woff2",
          weight: "700",
        },
      ],
    },
    ...ParticlesFonts,
    ...GrainFonts,
    ...ShimmerBottomFonts,
    ...ShimmerTopFonts,
    ...StarsFonts,
  ],
  { supportsExplicitInterCodegen: true },
);
export const __FramerMetadata__ = {
  exports: {
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    default: {
      type: "reactComponent",
      name: "FramerkZuk8wIV6",
      slots: [],
      annotations: {
        framerDisplayContentsDiv: "false",
        framerIntrinsicHeight: "400",
        framerIntrinsicWidth: "600",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"SZsOVWB1D":{"layout":["fixed","fixed"]}}}',
        framerImmutableVariables: "true",
        framerContractVersion: "1",
        framerComponentViewportWidth: "true",
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./kZuk8wIV6.map
